version: "3.1"

services:
  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookstore
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready
